[app-service]
registry-dir = "app-registry"

[app-service.addr]
ip = "0.0.0.0"
port = 8000

[scheduler-service]
schedules_dir = "schedules"

[scheduler-service.addr]
ip = "0.0.0.0"
port = 8010

[telemetry-service]
database = "telemetry.db"
direct_port = 8021

[telemetry-service.addr]
ip = "0.0.0.0"
port = 8020

[file-transfer-service]
storage_dir = "file-storage"
downlink_ip = "0.0.0.0"
downlink_port = 8080

[file-transfer-service.addr]
ip = "0.0.0.0"
port = 8040

[monitor-service.addr]
ip = "0.0.0.0"
port = 8030

[shell-service.addr]
ip = "0.0.0.0"
port = 8050

[payload-service.addr]
ip = "0.0.0.0"
port = 5001

[eps-service.addr]
ip = "0.0.0.0"
port = 5002

[radio-service.addr]
ip = "0.0.0.0"
port = 5003

[adcs-service.addr]
ip = "0.0.0.0"
port = 5004

[imu-service.addr]
ip = "0.0.0.0"
port = 5005